// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANeSCXvPUaSZMIBjJp_3McudAtcwO77Uo',
    appId: '1:1058517544161:web:b12ee7cb5c9ecf65b41ba0',
    messagingSenderId: '1058517544161',
    projectId: 'myfirstprojecttest-ccc10',
    authDomain: 'myfirstprojecttest-ccc10.firebaseapp.com',
    storageBucket: 'myfirstprojecttest-ccc10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBE-HEUyx9sFgcSlt0PGJaQYlk3Qgr_vc',
    appId: '1:1058517544161:android:d57b288954344742b41ba0',
    messagingSenderId: '1058517544161',
    projectId: 'myfirstprojecttest-ccc10',
    storageBucket: 'myfirstprojecttest-ccc10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCttBC4XFpUBB5Vjy50YxL-QcDwsIpHxYI',
    appId: '1:1058517544161:ios:2cecb01cc10d0ecdb41ba0',
    messagingSenderId: '1058517544161',
    projectId: 'myfirstprojecttest-ccc10',
    storageBucket: 'myfirstprojecttest-ccc10.appspot.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCttBC4XFpUBB5Vjy50YxL-QcDwsIpHxYI',
    appId: '1:1058517544161:ios:ee303c6c52efb681b41ba0',
    messagingSenderId: '1058517544161',
    projectId: 'myfirstprojecttest-ccc10',
    storageBucket: 'myfirstprojecttest-ccc10.appspot.com',
    iosBundleId: 'com.example.myfirstapp.RunnerTests',
  );
}
